2024-06-18 16:30:48,092 INFO    StreamThr :16892 [internal.py:wandb_internal():89] W&B internal server running at pid: 16892, started at: 2024-06-18 16:30:48.091518
2024-06-18 16:30:48,093 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: status
2024-06-18 16:30:48,100 INFO    WriterThread:16892 [datastore.py:open_for_write():85] open: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\run-f1hay5tw.wandb
2024-06-18 16:30:48,101 DEBUG   SenderThread:16892 [sender.py:send():379] send: header
2024-06-18 16:30:48,141 DEBUG   SenderThread:16892 [sender.py:send():379] send: run
2024-06-18 16:30:48,940 INFO    SenderThread:16892 [dir_watcher.py:__init__():211] watching files in: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files
2024-06-18 16:30:48,941 INFO    SenderThread:16892 [sender.py:_start_run_threads():1124] run started: f1hay5tw with start time 1718699448.092515
2024-06-18 16:30:48,941 DEBUG   SenderThread:16892 [sender.py:send_request():406] send_request: summary_record
2024-06-18 16:30:48,941 INFO    SenderThread:16892 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 16:30:48,950 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: check_version
2024-06-18 16:30:48,950 DEBUG   SenderThread:16892 [sender.py:send_request():406] send_request: check_version
2024-06-18 16:30:49,464 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: run_start
2024-06-18 16:30:49,481 DEBUG   HandlerThread:16892 [system_info.py:__init__():31] System info init
2024-06-18 16:30:49,481 DEBUG   HandlerThread:16892 [system_info.py:__init__():46] System info init done
2024-06-18 16:30:49,481 INFO    HandlerThread:16892 [system_monitor.py:start():181] Starting system monitor
2024-06-18 16:30:49,481 INFO    SystemMonitor:16892 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-06-18 16:30:49,481 INFO    HandlerThread:16892 [system_monitor.py:probe():201] Collecting system info
2024-06-18 16:30:49,486 INFO    SystemMonitor:16892 [interfaces.py:start():190] Started cpu monitoring
2024-06-18 16:30:49,486 INFO    SystemMonitor:16892 [interfaces.py:start():190] Started disk monitoring
2024-06-18 16:30:49,486 INFO    SystemMonitor:16892 [interfaces.py:start():190] Started gpu monitoring
2024-06-18 16:30:49,487 INFO    SystemMonitor:16892 [interfaces.py:start():190] Started memory monitoring
2024-06-18 16:30:49,494 INFO    SystemMonitor:16892 [interfaces.py:start():190] Started network monitoring
2024-06-18 16:30:49,498 DEBUG   HandlerThread:16892 [system_info.py:probe():195] Probing system
2024-06-18 16:30:49,499 DEBUG   HandlerThread:16892 [system_info.py:_probe_git():180] Probing git
2024-06-18 16:30:49,576 DEBUG   HandlerThread:16892 [system_info.py:_probe_git():188] Probing git done
2024-06-18 16:30:49,576 DEBUG   HandlerThread:16892 [system_info.py:probe():240] Probing system done
2024-06-18 16:30:49,576 DEBUG   HandlerThread:16892 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19041-SP0', 'python': '3.7.12', 'heartbeatAt': '2024-06-18T08:30:49.498689', 'startedAt': '2024-06-18T08:30:48.086535', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py', 'codePath': 'system\\main.py', 'git': {'remote': 'https://github.com/TsingZ0/PFLlib.git', 'commit': '004a405da7c159e843d98b2a53e2114d4f859912'}, 'email': '1731485214@qq.com', 'root': 'D:/Research-Projects-jupyter/PFLlib', 'host': 'DESKTOP-4LOGPS7', 'username': 'paddeyzhang', 'executable': 'D:\\Reseach Software\\envs\\fl\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2500.0, 'min': 0.0, 'max': 2500.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 0.0, 'max': 2500.0}], 'disk': {'total': 199.99901962280273, 'used': 69.3206787109375}, 'gpu': 'NVIDIA GeForce RTX 3070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070', 'memory_total': 8589934592}], 'memory': {'total': 15.842487335205078}}
2024-06-18 16:30:49,576 INFO    HandlerThread:16892 [system_monitor.py:probe():211] Finished collecting system info
2024-06-18 16:30:49,577 INFO    HandlerThread:16892 [system_monitor.py:probe():214] Publishing system info
2024-06-18 16:30:49,577 DEBUG   HandlerThread:16892 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-06-18 16:30:49,577 DEBUG   HandlerThread:16892 [system_info.py:_save_pip():67] Saving pip packages done
2024-06-18 16:30:49,577 DEBUG   HandlerThread:16892 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-06-18 16:30:49,578 ERROR   HandlerThread:16892 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-06-18 16:30:49,579 DEBUG   HandlerThread:16892 [system_info.py:_save_conda():86] Saving conda packages done
2024-06-18 16:30:49,579 DEBUG   HandlerThread:16892 [system_info.py:_save_code():89] Saving code
2024-06-18 16:30:49,619 DEBUG   HandlerThread:16892 [system_info.py:_save_code():110] Saving code done
2024-06-18 16:30:49,619 DEBUG   HandlerThread:16892 [system_info.py:_save_patches():127] Saving git patches
2024-06-18 16:30:49,954 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\wandb-summary.json
2024-06-18 16:30:49,954 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\conda-environment.yaml
2024-06-18 16:30:49,955 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\requirements.txt
2024-06-18 16:30:49,955 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\code\system\main.py
2024-06-18 16:30:49,955 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\code
2024-06-18 16:30:49,955 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\code\system
2024-06-18 16:30:50,563 DEBUG   HandlerThread:16892 [system_info.py:_save_patches():169] Saving git patches done
2024-06-18 16:30:50,564 INFO    HandlerThread:16892 [system_monitor.py:probe():216] Finished publishing system info
2024-06-18 16:30:50,566 DEBUG   SenderThread:16892 [sender.py:send():379] send: files
2024-06-18 16:30:50,566 INFO    SenderThread:16892 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2024-06-18 16:30:50,567 INFO    SenderThread:16892 [sender.py:_save_file():1375] saving file code\system\main.py with policy now
2024-06-18 16:30:50,567 INFO    SenderThread:16892 [sender.py:_save_file():1375] saving file diff.patch with policy now
2024-06-18 16:30:50,580 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 16:30:50,581 DEBUG   SenderThread:16892 [sender.py:send_request():406] send_request: stop_status
2024-06-18 16:30:50,958 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\diff.patch
2024-06-18 16:30:50,958 INFO    Thread-16 :16892 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_163048-f1hay5tw\files\wandb-metadata.json
2024-06-18 16:30:51,489 INFO    wandb-upload_0:16892 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmpzyvm6dx9wandb\s5gfvs0r-wandb-metadata.json
2024-06-18 16:30:55,628 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:00,685 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:05,754 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:10,798 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:11,991 WARNING FileStreamThread:16892 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/f1hay5tw/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022F8F2E6E48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000022F8D1FDF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/f1hay5tw/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2024-06-18 16:31:15,839 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:20,869 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:25,914 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 16:31:30,946 DEBUG   HandlerThread:16892 [handler.py:handle_request():144] handle_request: keepalive
