2024-06-18 10:32:34,155 INFO    StreamThr :25032 [internal.py:wandb_internal():89] W&B internal server running at pid: 25032, started at: 2024-06-18 10:32:34.155840
2024-06-18 10:32:34,156 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status
2024-06-18 10:32:34,164 INFO    WriterThread:25032 [datastore.py:open_for_write():85] open: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\run-43wkr34d.wandb
2024-06-18 10:32:34,165 DEBUG   SenderThread:25032 [sender.py:send():379] send: header
2024-06-18 10:32:34,207 DEBUG   SenderThread:25032 [sender.py:send():379] send: run
2024-06-18 10:32:35,019 INFO    SenderThread:25032 [dir_watcher.py:__init__():211] watching files in: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files
2024-06-18 10:32:35,019 INFO    SenderThread:25032 [sender.py:_start_run_threads():1124] run started: 43wkr34d with start time 1718677954.156836
2024-06-18 10:32:35,019 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: summary_record
2024-06-18 10:32:35,020 INFO    SenderThread:25032 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 10:32:35,027 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: check_version
2024-06-18 10:32:35,027 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: check_version
2024-06-18 10:32:36,033 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\wandb-summary.json
2024-06-18 10:32:36,367 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: run_start
2024-06-18 10:32:36,386 DEBUG   HandlerThread:25032 [system_info.py:__init__():31] System info init
2024-06-18 10:32:36,386 DEBUG   HandlerThread:25032 [system_info.py:__init__():46] System info init done
2024-06-18 10:32:36,386 INFO    HandlerThread:25032 [system_monitor.py:start():181] Starting system monitor
2024-06-18 10:32:36,387 INFO    SystemMonitor:25032 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-06-18 10:32:36,387 INFO    HandlerThread:25032 [system_monitor.py:probe():201] Collecting system info
2024-06-18 10:32:36,391 INFO    SystemMonitor:25032 [interfaces.py:start():190] Started cpu monitoring
2024-06-18 10:32:36,391 INFO    SystemMonitor:25032 [interfaces.py:start():190] Started disk monitoring
2024-06-18 10:32:36,392 INFO    SystemMonitor:25032 [interfaces.py:start():190] Started gpu monitoring
2024-06-18 10:32:36,392 INFO    SystemMonitor:25032 [interfaces.py:start():190] Started memory monitoring
2024-06-18 10:32:36,400 INFO    SystemMonitor:25032 [interfaces.py:start():190] Started network monitoring
2024-06-18 10:32:36,409 DEBUG   HandlerThread:25032 [system_info.py:probe():195] Probing system
2024-06-18 10:32:36,410 DEBUG   HandlerThread:25032 [system_info.py:_probe_git():180] Probing git
2024-06-18 10:32:36,489 DEBUG   HandlerThread:25032 [system_info.py:_probe_git():188] Probing git done
2024-06-18 10:32:36,489 DEBUG   HandlerThread:25032 [system_info.py:probe():240] Probing system done
2024-06-18 10:32:36,489 DEBUG   HandlerThread:25032 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19041-SP0', 'python': '3.7.12', 'heartbeatAt': '2024-06-18T02:32:36.409728', 'startedAt': '2024-06-18T02:32:34.149860', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py', 'codePath': 'system\\main.py', 'git': {'remote': 'https://github.com/TsingZ0/PFLlib.git', 'commit': '004a405da7c159e843d98b2a53e2114d4f859912'}, 'email': '1731485214@qq.com', 'root': 'D:/Research-Projects-jupyter/PFLlib', 'host': 'DESKTOP-4LOGPS7', 'username': 'paddeyzhang', 'executable': 'D:\\Reseach Software\\envs\\fl\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2500.0, 'min': 0.0, 'max': 2500.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 0.0, 'max': 2500.0}], 'disk': {'total': 199.99901962280273, 'used': 69.31438064575195}, 'gpu': 'NVIDIA GeForce RTX 3070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070', 'memory_total': 8589934592}], 'memory': {'total': 15.842487335205078}}
2024-06-18 10:32:36,489 INFO    HandlerThread:25032 [system_monitor.py:probe():211] Finished collecting system info
2024-06-18 10:32:36,489 INFO    HandlerThread:25032 [system_monitor.py:probe():214] Publishing system info
2024-06-18 10:32:36,489 DEBUG   HandlerThread:25032 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-06-18 10:32:36,490 DEBUG   HandlerThread:25032 [system_info.py:_save_pip():67] Saving pip packages done
2024-06-18 10:32:36,490 DEBUG   HandlerThread:25032 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-06-18 10:32:36,491 ERROR   HandlerThread:25032 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-06-18 10:32:36,492 DEBUG   HandlerThread:25032 [system_info.py:_save_conda():86] Saving conda packages done
2024-06-18 10:32:36,492 DEBUG   HandlerThread:25032 [system_info.py:_save_code():89] Saving code
2024-06-18 10:32:36,532 DEBUG   HandlerThread:25032 [system_info.py:_save_code():110] Saving code done
2024-06-18 10:32:36,532 DEBUG   HandlerThread:25032 [system_info.py:_save_patches():127] Saving git patches
2024-06-18 10:32:37,049 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\code\system\main.py
2024-06-18 10:32:37,049 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\requirements.txt
2024-06-18 10:32:37,049 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\conda-environment.yaml
2024-06-18 10:32:37,049 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\code
2024-06-18 10:32:37,050 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\code\system
2024-06-18 10:32:37,686 DEBUG   HandlerThread:25032 [system_info.py:_save_patches():169] Saving git patches done
2024-06-18 10:32:37,686 INFO    HandlerThread:25032 [system_monitor.py:probe():216] Finished publishing system info
2024-06-18 10:32:37,690 DEBUG   SenderThread:25032 [sender.py:send():379] send: files
2024-06-18 10:32:37,690 INFO    SenderThread:25032 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2024-06-18 10:32:37,690 INFO    SenderThread:25032 [sender.py:_save_file():1375] saving file code\system\main.py with policy now
2024-06-18 10:32:37,690 INFO    SenderThread:25032 [sender.py:_save_file():1375] saving file diff.patch with policy now
2024-06-18 10:32:37,703 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:32:37,704 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:32:38,061 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\diff.patch
2024-06-18 10:32:38,061 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\wandb-metadata.json
2024-06-18 10:32:38,308 DEBUG   SenderThread:25032 [sender.py:send():379] send: telemetry
2024-06-18 10:32:39,175 INFO    wandb-upload_2:25032 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmpjry36hcowandb\goweq8vt-diff.patch
2024-06-18 10:32:39,322 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:32:39,383 INFO    wandb-upload_1:25032 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmpjry36hcowandb\xc6080kg-code/system/main.py
2024-06-18 10:32:39,433 INFO    wandb-upload_0:25032 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmpjry36hcowandb\t4xegghn-wandb-metadata.json
2024-06-18 10:32:43,107 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\output.log
2024-06-18 10:32:44,761 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:32:45,125 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\output.log
2024-06-18 10:32:49,795 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:32:51,622 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: pause
2024-06-18 10:32:51,622 INFO    HandlerThread:25032 [handler.py:handle_request_pause():728] stopping system metrics thread or process
2024-06-18 10:32:51,622 INFO    HandlerThread:25032 [system_monitor.py:finish():190] Stopping system monitor
2024-06-18 10:32:51,622 DEBUG   SystemMonitor:25032 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-06-18 10:32:51,622 INFO    HandlerThread:25032 [interfaces.py:finish():202] Joined cpu monitor
2024-06-18 10:32:51,622 DEBUG   SystemMonitor:25032 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-06-18 10:32:51,628 INFO    HandlerThread:25032 [interfaces.py:finish():202] Joined disk monitor
2024-06-18 10:32:51,628 DEBUG   SystemMonitor:25032 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-06-18 10:32:51,674 INFO    HandlerThread:25032 [interfaces.py:finish():202] Joined gpu monitor
2024-06-18 10:32:51,675 INFO    HandlerThread:25032 [interfaces.py:finish():202] Joined memory monitor
2024-06-18 10:32:51,675 INFO    HandlerThread:25032 [interfaces.py:finish():202] Joined network monitor
2024-06-18 10:32:51,675 DEBUG   SenderThread:25032 [sender.py:send():379] send: stats
2024-06-18 10:32:52,722 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:32:52,722 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:32:54,958 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:00,014 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:05,069 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:06,295 INFO    Thread-16 :25032 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_103234-43wkr34d\files\config.yaml
2024-06-18 10:33:07,732 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:33:07,732 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:33:11,005 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:16,037 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:21,089 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:22,727 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:33:22,727 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:33:27,053 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:32,101 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:37,127 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:37,753 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:33:37,754 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:33:43,056 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:48,093 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:52,765 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:33:52,765 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:33:54,029 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:33:59,079 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:34:04,144 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 10:34:07,756 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 10:34:07,757 DEBUG   SenderThread:25032 [sender.py:send_request():406] send_request: stop_status
2024-06-18 10:34:11,831 INFO    SenderThread:25032 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 848, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))
2024-06-18 10:34:12,802 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:17,840 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:22,860 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:24,758 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:34:27,195 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:34:27,915 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:32,265 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:34:32,973 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:38,009 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:42,057 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:34:43,054 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:48,117 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:53,187 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:58,243 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:34:59,563 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:35:03,286 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:08,328 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:13,377 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:18,442 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:23,496 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:28,563 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:33,630 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:35,998 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:35:38,691 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:43,739 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:48,803 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:53,850 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:35:58,926 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:03,977 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:09,018 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:14,065 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:19,125 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:24,172 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:29,216 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:34,270 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:39,329 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:44,383 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:46,324 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:36:49,432 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:54,497 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:36:59,544 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:04,574 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:09,618 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:14,679 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:19,738 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:24,788 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:29,846 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:34,906 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:39,937 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:44,987 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:50,015 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:37:55,059 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:00,110 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:05,171 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:10,226 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:15,260 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:20,298 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:25,350 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:30,407 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:35,448 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:40,483 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:45,530 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:50,569 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:38:54,743 WARNING FileStreamThread:25032 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/43wkr34d/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001D26A91EF88>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/43wkr34d/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 10:38:55,602 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:00,645 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:05,684 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:10,744 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:15,786 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:20,831 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:25,881 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:30,929 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:35,967 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:41,013 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:46,085 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:51,124 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:39:56,180 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:01,239 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:06,298 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:11,357 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:16,393 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:21,442 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:26,477 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:31,523 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:36,558 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:41,602 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:46,652 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:51,674 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:40:56,723 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:01,782 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:06,813 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:11,849 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:16,888 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:21,931 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:26,964 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:31,990 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:37,024 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 10:41:42,051 DEBUG   HandlerThread:25032 [handler.py:handle_request():144] handle_request: keepalive
