2024-06-10 17:28:07,565 INFO    MainThread:21632 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_setup.py:_flush():76] Configure stats pid to 21632
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ly\.config\wandb\settings
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_setup.py:_flush():76] Loading settings from D:\Research-Projects-jupyter\PFLlib\system\wandb\settings
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'system\\main.py', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py'}
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_init.py:_log_setup():507] Logging user logs to D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240610_172807-pvft1f13\logs\debug.log
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_init.py:_log_setup():508] Logging internal logs to D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240610_172807-pvft1f13\logs\debug-internal.log
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_init.py:init():547] calling init triggers
2024-06-10 17:28:07,566 INFO    MainThread:21632 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {'goal': 'test', 'device': 'cuda', 'device_id': '0', 'dataset': 'Cifar10', 'num_classes': 10, 'model': BaseHeadSplit(
  (base): FedAvgCNN(
    (conv1): Sequential(
      (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    )
    (conv2): Sequential(
      (0): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    )
    (fc1): Sequential(
      (0): Linear(in_features=1600, out_features=512, bias=True)
      (1): ReLU(inplace=True)
    )
    (fc): Identity()
  )
  (head): Linear(in_features=512, out_features=10, bias=True)
), 'batch_size': 64, 'local_learning_rate': 0.005, 'learning_rate_decay': False, 'learning_rate_decay_gamma': 0.99, 'global_rounds': 1000, 'local_epochs': 1, 'algorithm': 'FedASCL', 'join_ratio': 1.0, 'random_join_ratio': False, 'num_clients': 20, 'prev': 0, 'times': 1, 'eval_gap': 10, 'save_folder_name': 'items', 'auto_break': False, 'dlg_eval': False, 'dlg_gap': 100, 'batch_num_per_client': 2, 'num_new_clients': 0, 'fine_tuning_epoch_new': 0, 'client_drop_rate': 0.0, 'train_slow_rate': 0.0, 'send_slow_rate': 0.0, 'time_select': False, 'time_threthold': 10000, 'beta': 0.0, 'lamda': 1.0, 'mu': 0.0, 'K': 5, 'p_learning_rate': 0.01, 'M': 5, 'itk': 4000, 'alphaK': 1.0, 'sigma': 1.0, 'alpha': 1.0, 'plocal_epochs': 1, 'tau': 1.0, 'fine_tuning_epochs': 10, 'dr_learning_rate': 0.0, 'L': 1.0, 'noise_dim': 512, 'generator_learning_rate': 0.005, 'hidden_dim': 512, 'server_epochs': 1000, 'localize_feature_extractor': False, 'server_learning_rate': 1.0, 'eta': 1.0, 'rand_percent': 80, 'layer_idx': 2, 'mentee_learning_rate': 0.005, 'T_start': 0.95, 'T_end': 0.98, 'momentum': 0.1, 'kl_weight': 0.0, 'wandb': 'SCL_test', 'margin_type': 'rcl', 'model_str': 'cnn', 'head': Linear(in_features=512, out_features=10, bias=True)}
2024-06-10 17:28:07,567 INFO    MainThread:21632 [wandb_init.py:init():572] re-initializing run, found existing run on stack: q67z14ef
2024-06-10 17:28:07,569 INFO    MainThread:21632 [wandb_run.py:_finish():1894] finishing run paddeyzhang/SCL_test/q67z14ef
2024-06-10 17:28:07,619 INFO    MainThread:21632 [jupyter.py:save_history():474] saving 2 cells to _session_history.ipynb
2024-06-10 17:28:07,619 INFO    MainThread:21632 [wandb_run.py:_config_callback():1282] config_cb ('_wandb', 'session_history') code\_session_history.ipynb None
2024-06-10 17:28:07,622 INFO    MainThread:21632 [jupyter.py:_save_ipynb():384] looking for notebook: SCL_Exps-jvsc-f030b701-b833-46c7-8430-b07a1d98f284e88941e3-e4b2-461d-a227-e54f53d9515b.ipynb
2024-06-10 17:28:07,623 INFO    MainThread:21632 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2024-06-10 17:28:07,623 INFO    MainThread:21632 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2024-06-10 17:28:07,623 INFO    MainThread:21632 [wandb_run.py:_restore():2111] restore
2024-06-10 17:28:07,623 INFO    MainThread:21632 [wandb_run.py:_restore():2117] restore done
2024-06-10 17:28:42,859 WARNING MsgRouterThr:21632 [router.py:message_loop():77] message_loop has been closed
2024-06-10 17:28:45,000 ERROR   MainThread:21632 [wandb_init.py:init():1175] error
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_init.py", line 581, in init
    latest_run.finish()
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 390, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 331, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 1885, in finish
    return self._finish(exit_code, quiet)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 1913, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_manager.py", line 223, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\service\service_sock.py", line 52, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
